// Lexico ES -> EN para equipos de laboratorio BioBase.
//
// Los nombres de los productos estan en espanol en Firebase, mientras que las
// carpetas de img/productos usan el slug ingles del catalogo BioBase. Este
// modulo traduce el nombre espanol a terminos comparables con esos slugs.
//
// JavaScript nativo: sin dependencias ni proceso de compilacion.

// Frases de varias palabras. Se aplican antes que el lexico palabra por palabra
// y de mayor a menor longitud, porque muchas resuelven ambiguedades que una
// traduccion palabra por palabra perderia (p.ej. "tipo suelo" = floor frente a
// "del suelo" = soil).
export const FRASES = {
    'de tipo suelo': 'floor',
    'tipo suelo': 'floor',
    'del suelo': 'soil',
    'de suelo': 'soil',
    'para suelos': 'soil',
    'banco de sangre': 'blood bank',
    'bolsas de sangre': 'blood bag',
    'banco de operaciones': 'operating table',
    'seguridad biologica': 'biological safety',
    'flujo laminar': 'laminar flow',
    'campana extractora de humo': 'fume hood',
    'extractor de humos': 'fume extractor',
    'caja de pase': 'pass box',
    'ducha de aire': 'air shower',
    'sistema de vci': 'ivc system',
    'jaulas para animales': 'animal cage',
    'arena para animales': 'animal litter',
    'estacion de trabajo': 'workstation',
    'nitrogeno liquido': 'liquid nitrogen',
    'hielo en copos': 'flake ice',
    'en cubos': 'cube',
    'perlas de vidrio': 'glass bead',
    'aire caliente': 'hot air',
    'lavadora desinfectadora': 'washer disinfector',
    'temperatura constante': 'constant temperature',
    'temperatura y humedad constantes': 'constant temperature humidity',
    'camara de estabilidad': 'stability chamber',
    'horno de mufla': 'muffle furnace',
    'horno de secado': 'drying oven',
    'aire forzado': 'forced air',
    'al vacio': 'vacuum',
    'alta temperatura': 'high temperature',
    'baja temperatura': 'low temperature',
    'baja velocidad': 'low speed',
    'alta velocidad': 'high speed',
    'gran capacidad': 'large capacity',
    'de sobremesa': 'table top benchtop',
    'tarjetas de gel': 'gel card',
    'sangre inmune': 'immune blood',
    'destapado automatico': 'auto decapping',
    'carbono y azufre': 'carbon sulfur',
    'aceite de cocina': 'cooking oil',
    'punto de inflamacion': 'flash point',
    'actividad del agua': 'water activity',
    'gases de escape': 'exhaust gas',
    'grasa fibra': 'fat fiber',
    'aparato kjeldahl': 'kjeldahl apparatus',
    'sello de placa': 'plate sealer',
    'bano seco': 'dry bath',
    'bano de agua': 'water bath',
    'desnaturalizacion e hibridacion': 'denaturation hybridization',
    'celda ultrasonica': 'ultrasonic cell',
    'bola mili': 'ball mill',
    'maquina de molienda': 'grinding mill',
    'potencial hidrico': 'water potential',
    'metales pesados': 'heavy metal',
    'no nuclear': 'non nuclear',
    'estructura de agregados': 'aggregate structure',
    'area foliar': 'leaf area',
    'frutas y verduras': 'fruit vegetable',
    'colonias bacterianas': 'bacterial colony',
    'muestreador de aire': 'air sampler',
    'tarro anaerobico': 'anaerobic jar',
    'placa caliente': 'hotplate',
    'reactor de vidrio encamisado': 'jacketed glass reactor',
    'descongelacion celular': 'cell thawing',
    'armario de seguridad': 'safety cabinet',
    'aguas residuales': 'wastewater',
    'agua pura': 'pure water',
    'acidos nucleicos': 'nucleic acid',
    'amplificacion genetica': 'gene amplification',
    'pcr cuantitativa fluorescente': 'fluorescence quantitative pcr',
    'quimica clinica': 'clinical chemistry',
    'tiras reactivas': 'test strip',
    'inclusion de tejidos': 'tissue embedding',
    'procesador automatizado de tejidos': 'automated tissue processor',
    'placa de enfriamiento': 'cooling plate',
    'tincion de tejidos': 'tissue stainer',
    'escaner de diapositivas': 'slide scanner',
    'gabinete de diapositivas': 'slide cabinet',
    'secador de portaobjetos': 'slide dryer',
    'flotacion de tejidos': 'tissue flotation',
    'absorcion atomica': 'atomic absorption',
    'espectrofotometro uv vis': 'uvvis spectrophotometer',
    'uv vis': 'uvvis',
    'estereo con zoom': 'stereo zoom',
    'dispensador de tapa de botella': 'bottle top dispenser',
    'rellenador de pipetas': 'pipette filler',
    'criba vibradora': 'vibrating screen shaker',
    'evaporador rotatorio': 'rotary evaporator',
    'colectores de filtracion': 'filtration manifold',
    'aparato de filtracion de disolventes': 'solvent filtration apparatus',
    'aparato de destilacion': 'distillation apparatus',
    'bomba peristaltica': 'peristaltic pump',
    'monitor de calefaccion': 'heating mantle',
    'selladora medica': 'medical sealer',
    'sellador de tubos': 'tube sealer',
    'silla para extraccion de sangre': 'blood donation chair',
    'monitor de recoleccion de sangre': 'blood collection monitor',
    'extractor de plasma': 'plasma extractor',
    'maquina para descongelar sangre': 'blood thawing machine',
    'calentador de sangre y fluidos': 'blood fluid warmer',
    'oximetro de pulso': 'pulse oximeter',
    'buscador de venas': 'vein finder',
    'sillon dental': 'dental chair',
    'silla de ruedas': 'wheelchair',
    'cama de hospital': 'hospital bed',
    'cama de exploracion': 'examination bed',
    'una sola manivela': 'single crank',
    'doble manivela': 'double crank',
    'tres manivelas': 'three crank',
    'maquina de turnos': 'queue machine',
    'ayuda para caminar': 'walking aid walker',
    'silla elevadora auxiliar para inodoro': 'toilet lift chair commode',
    'silla de bano': 'bath chair shower',
    'maquina de bano': 'bath machine',
    'carro de terapia': 'therapy trolley',
    'carro de acero inoxidable': 'stainless steel trolley',
    'frecuencia intermedia': 'intermediate frequency',
    'carrito de compras': 'shopping cart trolley',
    'sala limpia': 'cleanroom',
    'mobiliario de laboratorio': 'laboratory furniture',
    'laboratorio movil': 'mobile laboratory',
    'edificio modular': 'modular building',
    'almacenamiento en frio': 'cold storage',
    'aleacion de aluminio': 'aluminum alloy',
    'piso de pvc': 'pvc floor',
    'manejo de aire': 'air handling',
    'depilacion laser': 'laser hair removal',
    'luz pulsada intensa': 'intense pulsed light',
    'terapia de luz': 'light therapy',
    'adelgazamiento magnetico': 'magnetic slimming',
    'examen fisico': 'physical examination',
    'monitor fetal doppler': 'fetal doppler monitor',
    'terapia para la ictericia neonatal': 'neonatal jaundice therapy',
    'medidor de ictericia': 'jaundice meter',
    'incubadora infantil': 'infant incubator',
    'cama para ninos': 'child bed',
    'instrumento de terapia': 'therapy instrument',
    'cabina limpia': 'clean bench',
    'cabina de dispensacion': 'dispensing booth',
    'camara de aislamiento biologico': 'biological isolation chamber',
    'aislador de pollos y patos': 'chicken duck isolator',
    'lecho de flujo laminar': 'laminar flow bed',
    'estantes para congeladores': 'freezer rack',
    'cajas para congelador': 'freezer box',
    'caja de transporte': 'transport box',
    'congelador de la morgue': 'mortuary freezer',
    'autoclave de presion cilindrico horizontal': 'horizontal cylindrical pressure steam autoclave',
    'carro de desinfeccion uv': 'uv disinfection trolley',
    'robot de desinfeccion atomizador': 'atomizing disinfection robot',
    'cabina de esterilizacion uv con ozono': 'uv ozone sterilization cabinet',
    'gabinete de esterilizacion uv': 'uv sterilization cabinet',
    'esterilizador de aire': 'air sterilizer',
    'incubadora en agitacion': 'shaking incubator',
    'incubadora de iluminacion': 'lighting incubator',
    'incubadora de moho': 'mould incubator',
    'incubadora climatica': 'climate incubator',
    'incubadora bioquimica': 'biochemistry incubator',
    'centrifuga de citologia': 'cytology centrifuge',
    'centrifuga de hematocrito': 'hematocrit centrifuge',
    'centrifuga prp': 'prp centrifuge',
    'analizador de dqo': 'cod analyzer',
    'analizador de dbo': 'bod analyzer',
    'medidor de electroquimica': 'electrochemistry meter',
    'medidor de humedad de granos': 'grain moisture meter',
    'probador de fugas': 'leak tester',
    'probador de frascos': 'bottle tester',
    'probador de nutrientes': 'nutrient tester',
    'probador de enfermedades de las plantas': 'plant disease tester',
    'medidor de clorofila': 'chlorophyll meter',
    'medidor de tasa de transpiracion de plantas': 'plant transpiration rate meter',
    'medidor de espesor de hojas': 'leaf thickness meter',
    'medidor de temperatura de las hojas': 'leaf temperature meter',
    'medidor de respiracion': 'respiration meter',
    'respirador para': 'respiration',
    'contador automatico de semillas': 'automatic seed counter',
    'escaner de raiz': 'root scanner',
    'concentrador de muestras': 'sample concentrator',
    'disco duro': 'hard disk',
    'limpiadora ultrasonica': 'ultrasonic cleaner',
    'destilador de agua': 'water distiller',
    'suavizador de agua': 'water softener',
    'purificador de agua': 'water purifier',
    'purificador de aire': 'air purifier',
    'generador de gas': 'gas generator',
    'lector de microplacas': 'microplate reader',
    'lavadora de microplacas': 'microplate washer',
    'agitador de microplacas': 'microplate shaker',
    'centrifuga de microplacas': 'microplate centrifuge',
    'procesador automatico elisa': 'automatic elisa processor',
    'inmunoensayo por quimioluminiscencia': 'chemiluminescence immunoassay',
    'analizador de inmunoensayo de fluorescencia': 'fluorescence immunoassay analyzer',
    'analizador hematologico': 'hematology analyzer',
    'analizador de electrolitos': 'electrolyte analyzer',
    'analizador de coagulacion sanguinea': 'blood coagulation analyzer',
    'analizador de orina': 'urine analyzer',
    'analizador automatico de esr': 'automatic esr analyzer',
    'cama de hospital planas': 'flat hospital bed',
    'camas de hospital planas': 'flat hospital bed',
    'extractor de acidos nucleicos': 'nucleic acid extractor',
    'kit de extraccion de acidos nucleicos': 'nucleic acid extraction kit',
    'sistema automatizado de procesamiento de muestras': 'automated sample processing system',
    'dispensador automatico de microliquidos': 'automatic micro liquid dispenser',
    'dispensador de parafina': 'paraffin dispenser',
    'microtomo criostato': 'cryostat microtome',
    'sistema de tratamiento': 'treatment system',
    'sistema de agua pura': 'pure water system',
    'puerta de purificacion': 'purification door',
    'ventana de purificacion': 'purification window',
    'panel de purificacion': 'purification panel',
    'accesorios de purificacion': 'purification accessories',
    'sistema de ventilacion': 'ventilation system',
    'instrumento de examen fisico inteligente': 'intelligent physical examination instrument'
};

// Traduccion palabra por palabra. Un termino espanol puede expandirse a varios
// ingleses cuando el catalogo BioBase usa sinonimos indistintamente.
export const PALABRAS = {
    campana: 'hood cabinet',
    cabina: 'cabinet',
    gabinete: 'cabinet',
    armario: 'cabinet',
    seguridad: 'safety',
    bioseguridad: 'biosafety',
    biologica: 'biological',
    biologico: 'biological',
    certificada: 'certified',
    certificado: 'certified',
    clase: 'class',
    citotoxica: 'cytotoxic',
    radiologica: 'radiation',
    proteccion: 'protection',
    flujo: 'flow',
    laminar: 'laminar',
    humo: 'fume',
    humos: 'fume',
    extractora: 'extractor',
    extractor: 'extractor',
    limpia: 'clean',
    limpio: 'clean',
    dispensacion: 'dispensing',
    estacion: 'station',
    trabajo: 'work',
    patologia: 'pathology',
    camara: 'chamber',
    aislamiento: 'isolation',
    aislador: 'isolator',
    purificador: 'purifier',
    purificacion: 'purification',
    aire: 'air',
    caja: 'box',
    cajas: 'box',
    pase: 'pass',
    pollos: 'chicken',
    patos: 'duck',
    cambio: 'change',
    jaulas: 'cage',
    jaula: 'cage',
    animales: 'animal',
    arena: 'litter',
    vci: 'ivc',
    lecho: 'bed',
    medico: 'medical',
    medica: 'medical',
    ducha: 'shower',
    movil: 'mobile',
    refrigerador: 'refrigerator',
    refrigerada: 'refrigerated',
    refrigerado: 'refrigerated',
    sangre: 'blood',
    sanguinea: 'blood',
    congelador: 'freezer',
    congeladores: 'freezer',
    estantes: 'rack',
    incubadora: 'incubator',
    incubadoras: 'incubator',
    plaquetas: 'platelet',
    liofilizador: 'freeze dryer lyophilizer',
    transporte: 'transport',
    portatil: 'portable',
    maquina: 'machine',
    hielo: 'ice',
    contenedor: 'container tank',
    nitrogeno: 'nitrogen',
    morgue: 'mortuary',
    autoclave: 'autoclave',
    sobremesa: 'table top benchtop',
    serie: 'series',
    presion: 'pressure',
    cilindrico: 'cylindrical',
    horizontal: 'horizontal',
    vertical: 'vertical',
    portable: 'portable',
    esterilizador: 'sterilizer',
    esterilizacion: 'sterilization',
    carro: 'trolley cart',
    carrito: 'trolley cart',
    desinfeccion: 'disinfection',
    desinfectadora: 'disinfector',
    robot: 'robot',
    atomizador: 'atomizing',
    ozono: 'ozone',
    lavadora: 'washer',
    co2: 'co2',
    humedad: 'humidity',
    constante: 'constant',
    constantes: 'constant',
    multifuncional: 'multifunctional',
    bioquimica: 'biochemistry',
    climatica: 'climate',
    moho: 'mould',
    agitacion: 'shaking',
    estabilidad: 'stability',
    iluminacion: 'lighting',
    horno: 'oven',
    secado: 'drying',
    secador: 'dryer',
    vacio: 'vacuum',
    forzado: 'forced',
    alta: 'high',
    alto: 'high',
    baja: 'low',
    bajo: 'low',
    centrifuga: 'centrifuge',
    centrifugos: 'centrifuge',
    mini: 'mini',
    velocidad: 'speed',
    capacidad: 'capacity',
    gran: 'large',
    citologia: 'cytology',
    microplacas: 'microplate',
    microplaca: 'microplate',
    bolsas: 'bag',
    hematocrito: 'hematocrit',
    destapado: 'decapping',
    automatico: 'automatic auto',
    automatica: 'automatic auto',
    automatizado: 'automated',
    semiautomatico: 'semi automatic',
    inmune: 'immune',
    prp: 'prp',
    balanza: 'balance',
    analizador: 'analyzer',
    carbono: 'carbon',
    azufre: 'sulfur',
    colorimetro: 'colorimeter',
    probador: 'tester',
    densimetro: 'density meter',
    medidor: 'meter',
    granos: 'grain',
    electroquimica: 'electrochemistry',
    titulador: 'titrator',
    turbidimetro: 'turbidimeter',
    electroforesis: 'electrophoresis',
    automoviles: 'automobile car',
    fugas: 'leak',
    viscosimetro: 'viscometer',
    grasa: 'fat',
    fibra: 'fiber',
    kjeldahl: 'kjeldahl',
    gc: 'gas chromatograph',
    hplc: 'hplc liquid chromatograph',
    sello: 'sealer',
    sellador: 'sealer',
    selladora: 'sealer',
    placa: 'plate',
    placas: 'plate',
    bano: 'bath',
    seco: 'dry',
    disruptor: 'disruptor',
    celda: 'cell',
    celular: 'cell',
    ultrasonica: 'ultrasonic',
    ultrasonico: 'ultrasonic',
    desintegrador: 'disintegrator',
    molienda: 'grinding',
    homogeneizador: 'homogenizer',
    mufla: 'muffle',
    digestor: 'digester',
    concentrador: 'concentrator',
    muestras: 'sample',
    muestra: 'sample',
    tamiz: 'sieve',
    multiparametro: 'multiparameter',
    suelo: 'soil',
    suelos: 'soil',
    ph: 'ph',
    tensiometro: 'tensiometer',
    nutrientes: 'nutrient',
    escaner: 'scanner',
    raiz: 'root',
    hojas: 'leaf',
    hoja: 'leaf',
    foliar: 'leaf',
    clorofila: 'chlorophyll',
    transpiracion: 'transpiration',
    plantas: 'plant',
    planta: 'plant',
    espesor: 'thickness',
    enfermedades: 'disease',
    respirador: 'respiration',
    respiracion: 'respiration',
    frutas: 'fruit',
    verduras: 'vegetable',
    contador: 'counter',
    semillas: 'seed',
    silla: 'chair',
    sillon: 'chair',
    extraccion: 'extraction',
    monitor: 'monitor',
    recoleccion: 'collection',
    tubos: 'tube',
    tubo: 'tube',
    plasma: 'plasma',
    descongelar: 'thawing',
    descongelacion: 'thawing',
    microscopio: 'microscope',
    monocular: 'monocular',
    binocular: 'binocular',
    trinocular: 'trinocular',
    digital: 'digital',
    fluorescente: 'fluorescence',
    fluorescencia: 'fluorescence',
    invertido: 'inverted',
    metalurgico: 'metallurgical',
    didactico: 'student educational',
    estereo: 'stereo',
    polarimetro: 'polarimeter',
    refractometro: 'refractometer',
    espectrofotometro: 'spectrophotometer',
    microvolumen: 'micro volume',
    llama: 'flame',
    atomica: 'atomic',
    nir: 'nir',
    dispensador: 'dispenser',
    microliquidos: 'micro liquid',
    pipetas: 'pipette',
    pipeta: 'pipette',
    rellenador: 'filler',
    electronica: 'electronic',
    electronico: 'electronic',
    botella: 'bottle',
    frascos: 'bottle',
    agitador: 'shaker stirrer',
    vibradora: 'vibrating',
    criba: 'screen sieve',
    evaporador: 'evaporator',
    rotatorio: 'rotary',
    colectores: 'manifold',
    filtracion: 'filtration',
    disolventes: 'solvent',
    destilacion: 'distillation',
    destilador: 'distiller',
    bomba: 'pump',
    peristaltica: 'peristaltic',
    tarro: 'jar',
    anaerobico: 'anaerobic',
    bacterianas: 'bacterial',
    colonias: 'colony',
    muestreador: 'sampler',
    agua: 'water',
    aguas: 'water',
    circulador: 'circulator',
    enfriador: 'chiller',
    enfriamiento: 'cooling',
    caliente: 'hot',
    calefaccion: 'heating',
    calentador: 'warmer',
    deshumidificador: 'dehumidifier',
    lavaojos: 'eyewash',
    generador: 'generator',
    gas: 'gas',
    reactor: 'reactor',
    vidrio: 'glass',
    encamisado: 'jacketed',
    instrumento: 'instrument',
    limpiadora: 'cleaner',
    suavizador: 'softener',
    residuales: 'waste',
    pura: 'pure',
    tratamiento: 'treatment',
    microtomo: 'microtome',
    criostato: 'cryostat',
    procesador: 'processor',
    procesamiento: 'processing',
    tejidos: 'tissue',
    parafina: 'paraffin',
    trimmer: 'trimmer',
    inclusion: 'embedding',
    centro: 'center',
    tincion: 'stainer staining',
    diapositivas: 'slide',
    portaobjetos: 'slide',
    flotacion: 'flotation',
    quimica: 'chemistry',
    quimico: 'chemistry',
    semi: 'semi',
    inmunoensayo: 'immunoassay',
    quimioluminiscencia: 'chemiluminescence',
    elisa: 'elisa',
    lector: 'reader',
    hematologico: 'hematology',
    hematologia: 'hematology',
    electrolitos: 'electrolyte',
    electrolitico: 'electrolyte',
    coagulacion: 'coagulation',
    esr: 'esr',
    orina: 'urine',
    acidos: 'acid',
    nucleicos: 'nucleic',
    amplificacion: 'amplification',
    genetica: 'gene',
    pcr: 'pcr',
    cuantitativa: 'quantitative',
    deteccion: 'detection',
    reactivos: 'reagent',
    reactivo: 'reagent',
    recativos: 'reagent',
    clinica: 'clinical',
    clia: 'clia',
    poct: 'poct',
    kit: 'kit',
    tiras: 'strip',
    infantil: 'infant',
    bebes: 'baby infant',
    ninos: 'child',
    ictericia: 'jaundice',
    neonatal: 'neonatal',
    fetal: 'fetal',
    doppler: 'doppler',
    inteligente: 'intelligent',
    cama: 'bed',
    camas: 'bed',
    dental: 'dental',
    oximetro: 'oximeter',
    pulso: 'pulse',
    venas: 'vein',
    fluidos: 'fluid',
    dea: 'aed',
    hospital: 'hospital',
    plana: 'flat',
    planas: 'flat',
    manivela: 'crank',
    manivelas: 'crank',
    electrica: 'electric',
    electrico: 'electric',
    exploracion: 'examination',
    ruedas: 'wheel',
    turnos: 'queue',
    baston: 'cane crutch',
    caminar: 'walking',
    elevadora: 'lift',
    inodoro: 'toilet commode',
    terapia: 'therapy',
    acero: 'steel',
    inoxidable: 'stainless',
    frecuencia: 'frequency',
    intermedia: 'intermediate',
    compras: 'shopping',
    sala: 'room',
    mobiliario: 'furniture',
    laboratorio: 'laboratory lab',
    edificio: 'building',
    edificios: 'building',
    modular: 'modular',
    almacenamiento: 'storage',
    frio: 'cold',
    puerta: 'door',
    ventana: 'window',
    aleacion: 'alloy',
    aluminio: 'aluminum',
    panel: 'panel',
    piso: 'floor',
    pvc: 'pvc',
    manejo: 'handling',
    ventilacion: 'ventilation',
    filtros: 'filter',
    filtro: 'filter',
    accesorios: 'accessories',
    depilacion: 'hair removal',
    laser: 'laser',
    semiconductor: 'semiconductor',
    adelgazamiento: 'slimming',
    magnetico: 'magnetic',
    luz: 'light',
    pulsada: 'pulsed',
    intensa: 'intense',
    dispositivo: 'device',
    sistema: 'system',
    aparato: 'apparatus',
    oficinas: 'office',
    fabricas: 'factory',
    temperatura: 'temperature',
    microondas: 'microwave',
    molino: 'mill',
    mezclador: 'mixer',
    bola: 'ball',
    mili: 'mill',
    operaciones: 'operating',
    banco: 'bank bench',
    hibridacion: 'hybridization',
    desnaturalizacion: 'denaturation',
    cocina: 'cooking',
    aceite: 'oil',
    inflamacion: 'flash',
    escape: 'exhaust',
    gases: 'gas',
    actividad: 'activity',
    potencial: 'potential',
    hidrico: 'water',
    pesados: 'heavy',
    metales: 'metal',
    agregados: 'aggregate',
    estructura: 'structure',
    nuclear: 'nuclear',
    tasa: 'rate',
    area: 'area',
    copos: 'flake',
    cubos: 'cube',
    perlas: 'bead',
    liquido: 'liquid',
    liquida: 'liquid',
    liquidos: 'liquid',
    microliquido: 'micro liquid',
    dqo: 'cod',
    dbo: 'bod',
    vis: 'vis',
    uv: 'uv',
    nsf: 'nsf',
    en: 'en',
    iii: 'iii',
    ii: 'ii',
    i: 'i',
    a2: 'a2',
    b2: 'b2',
    levo: 'levo',
    plus: 'plus',
    bke: 'bke',
    doble: 'double',
    cara: 'side',
    cell: 'cell',
    superado: '',
    pregunta: '',
    nuestros: '',
    servicios: 'service',
    mantenimiento: 'maintenance'
};

// Palabras sin valor discriminante al comparar con los slugs.
export const VACIAS = new Set([
    'de', 'del', 'la', 'el', 'los', 'las', 'y', 'e', 'o', 'u', 'a', 'al',
    'para', 'con', 'sin', 'por', 'un', 'una', 'unos', 'unas', 'en', 'su',
    'tipo', 'the', 'of', 'and', 'for', 'with', 'to'
]);
